### ISSUE TITLE
Android, fails to install 1.22 files.

### ISSUE THREAD

**Issue by freijie** [ElonaFoobar/ElonaFoobar#949]
# Environment

* OS version: Android 7.1.2 MIUI 9.6
* Elona foobar verision: 0.2.8

# Details
Crash during installation upo selecting elona 1.22 zip file.

# How to reproduce
Install foobar, start, select elona 1.22 on eith internal memory or sd card, press "open", get a crash.

# Cause
Crashlog:

java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
	at xyz.ki.elonafoobar.SplashScreen.verifyArchiveFile(SplashScreen.java:128)
	at xyz.ki.elonafoobar.SplashScreen.extractArchiveFile(SplashScreen.java:150)
	at xyz.ki.elonafoobar.SplashScreen.onResume(SplashScreen.java:190)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
	at android.app.Activity.performResume(Activity.java:6984)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3477)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3540)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6228)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

optional

# Solution

optional

**Comment by Ruin0x11** [comment]
Likely due to the minimum Android version targeted. In Elona_foobar, `targetSdkVersion` is currently `28`.

**Comment by Ruin0x11** [comment]
Closed by #952.
